name: Test Course Link Getter

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r course_link_getter/requirements.txt
    
    - name: Run tests
      run: |
        cd course_link_getter
        python -m pytest tests/test_store.py -v --tb=short
    
    - name: Run tests with coverage
      run: |
        cd course_link_getter
        pip install pytest-cov
        python -m pytest tests/test_store.py --cov=core --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./course_link_getter/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
